import Navbar from "@/components/Navbar";
import { ClerkProvider, UserButton } from "@clerk/nextjs/app-beta";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider>
        <body>
          <Navbar userButton={<UserButton afterSignOutUrl="/" />} />
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}
